### ISSUE TITLE
Switch Selector not translating its option text. 

### ISSUE THREAD

**Issue by YashMaurya9274** [jkdrangel/react-native-switch-selector#6]
I have come across a problem ---> I'm using translations in my project and by default the language selected is English but whenever I change my translations to Hindi or any other language the "Yes or No" options in my Switch Selector does not change.

PS - the values in the switch selector for attribute "options" is defined in some other .js file and are being accessed from there
eg. translation.js --> LOGIN_WITH_SAME_EMAIL_ID =  [
  { label: "yes", value: strings.yes },
  { label: "no", value: strings.no },
]; 

// strings.js is another file containing translations of yes and no in different languages.

and 

<SwitchSelector
  initial={0}
  onPress={(value) => {//some function}}
  options={GLOBALS.LOGIN_WITH_SAME_EMAIL_ID}
/>

here the value is only converted when I go to translation.js and do a force save on the file..!
but when I use the direct way i.e. directly initializing "options" it works...
but I need to use the previous way, because all the translations should be accessed from an external .js file only.!

**Comment by jkdrangel** [comment]
@YashMaurya9274 sorry for the very large delay, but the problem is you're not change the label.
