### ISSUE TITLE
Can't npm install

### ISSUE THREAD

**Issue by OshedheMunasinghe** [jkdrangel/react-native-switch-selector#9]
```
$ npm i @jkdrangel/react-native-switch-selector --save
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@jkdrangel%2freact-native-switch-selector - Not found
npm ERR! 404
npm ERR! 404  '@jkdrangel/react-native-switch-selector@*' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\-

```
If you look from the npm page on right corner it says to install: **npm i react-native-switch-selector**
which is wrong because you can't import by this script: **import SwitchSelector from "@jkdrangel/react-native-switch-selector";**

it will return error 
I hope you can fix the bug :) 

_Ps. I am not using Expo!_

**Comment by kokone** [comment]
This is quite old but in case anyone finds this later, run `npm i react-native-switch-selector` instead.
See: https://www.npmjs.com/package/react-native-switch-selector

**Comment by jkdrangel** [comment]
@kokone thanks for the reply. I'll change the readme to fix this.
